---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: express
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: express
  source:
    repoURL: https://github.com/amit-gueta/argo-express-prod.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
