---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 34.105.179.16.nip.io
  namespace: dev
spec:
  ingressClassName: nginx
  rules:
  - host: 34.105.179.16.nip.io
    http:
      paths:
      - backend:
          service:
            name: express-server1
            port:
              number: 3000
        path: /
        pathType: Prefix
status:
  loadBalancer: {}