---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: amitgu-dev-ingress
  namespace: prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - amitgu.dev
    secretName: secret-tls
  rules:
  - host: amitgu.dev
    http:
      paths:
      - backend:
          service:
            name: express-server
            port:
              number: 3000
        path: /
        pathType: Prefix
status:
  loadBalancer: {}