apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: express-app
  namespace: production
spec:
  project: default
  source:
    repoURL: https://github.com/amit-gueta/express-app.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: production